language: python
sudo: required

python:
    - "2.7"
  
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - wget https://raw.githubusercontent.com/alexdobin/STAR/master/bin/Linux_x86_64/STAR
  - chmod +x STAR
  - mkdir $HOME/bin
  - cp STAR $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - mkdir $HOME/tmp
  - export TMPDIR=$HOME/tmp

install:
    - conda create -q -n testenv --yes python=2.7 numpy scipy pandas cython
    - source activate testenv
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda install pysam
    - conda install -c anaconda setuptools=27.2.0
    - conda install -c conda-forge regex=2017.04.05
    - python setup.py build
    - python setup.py install
   
script:
    - python setup.py test

after_success:
    - coveralls
  
notifications:
    email: false
